<html>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

.image-thumbnail {
    position: relative;
    display: inline;  
    padding-left: 45px;
}

.bottom-right {
    margin-top: -24px;

}
.image-name {

     color: black;
  padding: 0px 32px 9px 43px;
}


</style>

<div class = "content-image" style=" display: flow-root;">
    <?php


        $total = 0; 
        $count = 1;

        foreach ($block->getFilestatusCollection() as $key=>$filestatus){
              /*echo
                    '<div class = "image-thumbnail">
                        <img class ="thumbnail" src="'.$block->getMediaimg($filestatus->getFileName()).'"  id = "'.$filestatus->getFileId().'">

                        <div class = "bottom-right"> '.$filestatus->getFileSize().'Kb</div>
                        <div class = "image-name">'.$filestatus->getFileName().'</div>
                    </div>';  */  
                    $file_name = "";
                    if(strlen($filestatus->getFileName())>36){
                        $file_name = "...".substr($filestatus->getFileName(), strlen($filestatus->getFileName())-28);
                    } else {
                        $file_name = $filestatus->getFileName();
                    }
                echo
                    '<div class="responsive">
                      <div class="gallery">
                          <img class = "thumbnail" src="'.$block->getMediaimg($filestatus->getFileName()).'" alt="Trolltunga Norway" onclick="openModal();currentSlide('.$count.')" >
                        
                        <div class = "bottom-right"> '.$filestatus->getFileSize().'Kb</div>
                        <div class="desc">'.$file_name.'</div>
                      </div>
                    </div>';
                $count = $count + 1;
                $total = $total + 1; 


        }
    ?>
</div>

    <!--pagination-->
<center>
    <div class = "pagination">
            <?php if ( !isset($_GET['page'])|| $_GET['page'] ==1)
            {
                if($block->getSizeCollect()<12){
                    echo 'Display '.$block->getSizeCollect().'/'.$block->getSizeCollect().' image(s)';
                } else {
                    echo '<a href="?page=2" >Next page</a>&nbsp; (12/'.$block->getSizeCollect().')';
                }

            }  else
            {
                $page = $_GET['page'];
                echo '<a href="?page='.($page -1).'" >Previous page</a>';
                 if(($page*12)< $block->getSizeCollect()){
                    echo '	&nbsp;	&nbsp;|	&nbsp;
                        <label> page  '. $page.' ('.($page*12 -12).'-'.($page*12).'/'.$block->getSizeCollect().')</label> 	&nbsp;	|&nbsp;	&nbsp;
                        <a href="?page='.($page +1).'" >Next page</a>';
                 } else {
                     echo '&nbsp;	&nbsp;|	&nbsp;<label>Last page ('.($page*12 -12).'-'.($block->getSizeCollect()).'/'.$block->getSizeCollect().')</label>';
                 }
            }?>

    </div>
</center>
<div id="myModal" class="modal fade" role="dialog">
  <span class="close cursor" onclick="closeModal()">&times;</span>
  <div class="modal-content">


    <?php
        $count = 1;
        foreach ($block->getFilestatusCollection() as $key=>$filestatus){

                echo '
                 <div class="mySlides">
                  <div class="numbertext">'.$count.'/'. $total.'</div>
                  <img src="'.$block->getMediaimg($filestatus->getFileName()).'" style="width: auto;height: 600px;">
                </div>
                ';
                 $count = $count +1;


        }
    ?>
    
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

    <div class="caption-container">
      <p id="caption"></p>
    </div>
    <?php
        $count = 1;
        foreach ($block->getFilestatusCollection() as $key=>$filestatus){
                echo '
                  <div class="column-model-below">
                  <img class="demo cursor" src="'.$block->getMediaimg($filestatus->getFileName()).'"  onclick="currentSlide('.$count.')" alt="'.$filestatus->getFileName().'">
                </div>
                ';
                $count = $count +1;
        }
    ?>
  </div>
</div>
<style>

.pagination {
    margin-top: 13px;
    font-size: 20px;
}

body {
  font-family: Verdana, sans-serif;
  margin: 0;
}

* {
  box-sizing: border-box;
}

.row > .column {
  padding: 0 8px;
}

.row:after {
  content: "";
  display: table;
  clear: both;
}

.column-model-below {
  float: left;

}

/* The Modal (background) */
.modal {
  display: none;
  position: fixed;
  z-index: 1;
  padding-top: 100px;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: auto;
  background-color: black;
}

/* Modal Content */
.modal-content {
  position: relative;
  background-color: #fefefe;
  margin: auto;
  padding: 0;
  width: 90%;
  max-width: 1000px;
}

/* The Close Button */
.close {
  color: white;
  position: absolute;
  top: 10px;
  right: 25px;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: #999;
  text-decoration: none;
  cursor: pointer;
}

.mySlides {
  display: none;
  background-color: black;
  text-align: center;
}

.cursor {
    cursor: pointer;
    border-radius: 20px;
    padding: 10px;
    width: 150px;
    height: 150px;
}

/* Next & previous buttons */
.prev,
.next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -50px;
  color: white;
  font-weight: bold;
  font-size: 20px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
  -webkit-user-select: none;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover,
.next:hover {
  background-color: rgba(0, 0, 0, 0.8);
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 4px 500px;
  position: absolute;
  top: 0;
}

img {
  margin-bottom: -4px;
}

.caption-container {
  text-align: center;
  background-color: black;
  padding: 2px 16px;
  color: white;
}

.demo {
  opacity: 0.6;
}

.active,
.demo:hover {
  opacity: 1;
}

img.hover-shadow {
  transition: 0.3s
}

.hover-shadow:hover {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)
}


div.gallery {
    border: 1px solid #ccc;
}

div.gallery:hover {
    border: 1px solid #777;
}

div.gallery img {
    width: 300px;
    height: 200px;
}

div.desc {
    padding: 15px;
    text-align: center;
}

* {
    box-sizing: border-box;
}

.responsive {
    padding: 6px 6px;
    float: left;
    width: 15.99999%;
    cursor: pointer;
}

@media only screen and (max-width: 700px) {
    .responsive {
        width: 49.99999%;
        margin: 6px 0;
    }
}

@media only screen and (max-width: 500px) {
    .responsive {
        width: 100%;
    }
}

.clearfix:after {
    content: "";
    display: table;
    clear: both;
}
</style>





<div class="clearfix"></div>
<script>
function openModal() {
  document.getElementById('myModal').style.display = "block";
}

function closeModal() {
  document.getElementById('myModal').style.display = "none";
}

var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  var captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>
</br></br>
<a href="../uploadfile/" class="action subscribe primary" role="button">Upload image </a>
</body>
</html>	 